### PR TITLE
Ex2 (main program and tree module)

### PR DESCRIPTION
**Pull request by helena-rg**
Hi, sorry for the inconvenience, but I realised that I made a commit (when I start to work on exercise 2) in the ex1 file (only in the input and output files) and I have been tried to revert it, although it remains there :'(

### CODE REVIEW

**Comment by helena-rg** [comment]
Sorry again, but I tried to parallelise the code of exercise 2, and I think it is working well (I tested with 1000 and 5000 particles and the computational time has decreased significantly). However, I have some questions about it.

At first I was only trying to parallelise the loop that calculate the interaction between particles, so I could introduce in omp parallel private variable (like thread id and number of threads) and shared like the accelerations and the target cell; but when I include the workshare construct, the parallel block must be in the main code not in the module. I was wondering if a conditional could be added in the module, so in the case you want to use Calculate_forces, it wouldn't be necessary to have opened a parallel block.

Also, with the workshare construct, I don't know if I have to include private/shared variables. I think it's not necessary, but I am not sure.

**Comment by helena-rg** [comment]
Hi Hannu, 
Sorry again, I just want to consult something about OpenMP (shared/private) variables. I think all the variables are shared in my program (because any of them is defined as private). I thought this shouldn't be a issue, because acceleration is the variable that it is changing in the do loop, and every iteration is done in a given index (acceleration(goal), where goal is the index of the particle). Therefore, it shouldn't matter if these variables are shared (so all threads have access to them). Maybe the index of the loop should be private, but right now the code works and I don't identify problems in the results. 
Another change that I thought, it is to include in the initial tree an omp parallel, however I don't think this could change the computational time a lot in the simulation.

**Comment by hpparvi** [comment]
Hi Helena,
The parallelisation looks fine. The variables have a default status if this isn't explicitly given. In general, it is better to set the status explicitly, but in your main code, you're using only workshare and single environments, and that works fine. The important thing is that you're setting the private variables correctly private in your `calculate_forces` routine.

So, everything looks good at a quick glance (well, I'd prefer to have the sharing status of the variables also defined in the main program, but that's not a major issue ;)  )  

The only thing I'm a bit curious about is the evaluation time table in your Readme. It would seem that the OpenMP runs are significantly lower than the serial runs. Are you sure you haven't swapped the columns by accident?

**Comment by helena-rg** [comment]
Yes!! Sorry I didn't realise before. I already change the Readme, so I think it's fixed now. It's true that I should add the shared status for head, particles and acc. I would try to change it tomorrow (but in this case I think it should not give any issue even without it, I hope :')). Thanks!!

**Pull request merged**
